version: '2'

# Services
# -----------------------------------------------------------------------------
services:

    # Database
    # ------------------------------
    db:
        image: mariadb
        env_file: ./.env

    # WordPress (PHP container)
    # ------------------------------
    wp:
        image: dbooom/docker-wp-cli
        volumes:
            - data:/usr/share/nginx/html
        links:
            - db:database
        env_file: ./.env

    # Web server
    # ------------------------------
    web-server:
        image: dbooom/docker-nginx-with-templates
        volumes_from:
            - wp
        links:
            - wp:php
        ports:
            - "80:80"
            - "443:443"
        env_file: ./.env

# Volumes
# -----------------------------------------------------------------------------
volumes:
    data:
        driver: local
